---
exclude_paths:
  - spec/fixtures
  - 'lib/rapid-vaults/bindings/rapid-vaults*.rb'

detectors:
  TooManyStatements:
    enabled: false

  NestedIterators:
    enabled: false

  LongParameterList:
    enabled: false

  UncommunicativeVariableName:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  NilCheck:
    enabled: false
