---
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'bin/*.rb'
    - 'spec/**/*.rb'
    - rapid-vaults.gemspec
    - Gemfile
    - Rakefile
    - Vagrantfile
  Exclude:
    - 'spec/fixtures/**/*'
    - 'lib/rapid-vaults/bindings/rapid_vaults*.rb'

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
