# setup environment
dist: trusty
sudo: false
language: ruby
cache: bundler

notifications:
  email: false

git:
  depth: 5

# setup tests
matrix:
  include:
    - rvm: 2.1.10
      env: TEST='unit system'
    - rvm: 2.2.9
      env: TEST=default
    - rvm: 2.3.6
      env: TEST='unit system'
    - rvm: 2.4.3
      env: TEST='unit system'
    - rvm: 2.5.0
      env: TEST='unit system'
  allow_failures:
    - rvm: 2.4.3
    - rvm: 2.5.0

# execute tests
before_install: gem update --no-document bundler
install: bundle install --retry=3
script: bundle exec rake $TEST
