# setup environment
dist: xenial
language: ruby
cache: bundler

notifications:
  email: false

git:
  depth: 5

# setup tests
matrix:
  include:
    - rvm: 2.2
      env: TEST='grpc unit system'
    - rvm: 2.3
      env: TEST=default
    - rvm: 2.4
      env: TEST='grpc unit system'
    - rvm: 2.5
      env: TEST='grpc unit system'
    - rvm: 2.6
      env: TEST='grpc unit system'
    - rvm: 2.7
      env: TEST='grpc unit system'
  allow_failures:
    - rvm: 2.7

# execute tests
before_install: gem update --no-document bundler
install: bundle install --retry=3
script: bundle exec rake $TEST
