# setup environment
dist: focal
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
matrix:
  include:
  - rvm: 2.5
    env: TEST='grpc unit system'
  - rvm: 2.6
    env: TEST='grpc unit system'
  - rvm: 2.7
    env: TEST=default
  - rvm: 3.0
    env: TEST='grpc unit system'
  - rvm: 3.1
    env: TEST='grpc unit system'

# execute tests
before_install: gem update --no-document bundler
install: bundle install --retry=3
script: bundle exec rake $TEST
