---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    parameters:
      ruby-version:
        type: string
    docker:
    - image: ruby:<< parameters.ruby-version >>-slim
    resource_class: small
    steps:
    - checkout
    - restore_cache:
        keys:
        - rapid-vaults-ruby-<< parameters.ruby-version >>
    - run:
        name: package prereqs install
        command: apt-get update && apt-get install -y gcc libgpgme-dev
    - run:
        name: bundler install
        command: bundle config build.gpgme --use-system-libraries && bundle install --retry=3
    - save_cache:
        paths:
        - ~/.bundle
        key: rapid-vaults-ruby-<< parameters.ruby-version >>
    - run:
        name: execute tests
        command: bundle exec rake grpc unit system

workflows:
  execute_tests:
    jobs:
    - test:
        matrix:
          parameters:
            ruby-version:
            - '2.4'
            - '2.5'
            - '2.6'
            - '2.7'
            - '3.0'
